name: 'Production Environment Variables On Flag'
description: 'Use one set of environment variables based on iProd boolean variable value'
author: 'Chad Lee'

inputs:
  keys:
    description: 'The environment variables to search replace with production values.'
    required: true
  isProd:
    description: 'Is prod environment active?'
    required: false
    default: false

runs:
  using: 'node12'
  main: 'dist/index.js'

branding:
  icon: 'sliders'
  color: 'red'
